stages:
  - Dev-site
  #- Test-site
  #- Staging-site
  #- Prod-site

Deploy in Dev Site:
  stage: Dev-site
  script:
    #- ssh -t -o "StrictHostKeyChecking=no" -p 52448 poitore@192.168.17.244 /bin/bash -s << EOT
    - ssh -p 52448 poitore@192.168.17.209 /bin/bash << EOT
    - cd /home/poitore/poitore-api/poitore-api-graphql
    - git pull
    - npm install
    - pm2 status
    - pm2 del all
    - pm2 start --name poitore-api app.js
    #- pm2 serve build 13001 --name poitore-api --spa
    - pm2 save
    - pm2 restart 0
    - pm2 status
  only:
    - master
  tags:
    - shell
  #when: manual